### ISSUE TITLE
Mention using event bubbling. 

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/handlebars#7]
Since you can't add events before you've rendered the template.

**Comment by jrhorn424** [comment]
:+1:

**Comment by RealWeeks** [comment]
@gaand added question as reminder to consultant to mention in commit  fd8be0f

**Comment by gaand** [comment]
@J-Weeks I'm not seeing that in the commit you linked.

**Comment by MicFin** [comment]
@gaand @jrhorn424 Event bubbling generally leads into a discussion about event delegation, do we want to add these topics during this talk?  My instinct is that it may not necessarily be ideal in the handlebars talk but I have a few ideas of how to work it in if we think it is the best place for it.

**Comment by jrhorn424** [comment]
They run into it as soon as they use dynamic rendering.

**Comment by gaand** [comment]
I think this is where it needs to get covered since this is what causes problems when not taking it into account.

**Comment by MicFin** [comment]
@gaand @jrhorn424 
May I add a demo section to the repo that will cover...
1.  Trying to add a click event on the dynamic template content (it can simply change the font color of the element clicked)
2.  Having the click event not work because the elements are not yet in the DOM 
3.  Explain event bubbling 
4.  Then show solving the failing click event using event delegation

During this demo, I can also show how to use a dynamic ID in a template as suggested in issue 
https://github.com/ga-wdi-boston/handlebars-client/issues/9 
```html
<li data-id-"{{this.id}}">{{this.name}}</li>
```
